services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mohlakoana
      POSTGRES_PASSWORD: mohlakoana
      POSTGRES_DB: mohlakoana
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

volumes:
  postgres_data:
